name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  SN_RELEASE: fast

jobs:
  unix_build:
    name: Unix build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            uploaded_filename: scip-json-cli-x86_64-apple-darwin

          - os: ubuntu-latest
            uploaded_filename: scip-json-cli-x86_64-pc-linux
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1

      - name: Test and build binary
        run: scala-cli package --native generated test.scala -f -o scip-json-cli --native-mode release-fast

      - uses: actions/upload-artifact@master
        with:
          path: scip-json-cli
          name: ${{ matrix.uploaded_filename }}

  windows_build:
    name: Windows build
    strategy:
      fail-fast: false
    runs-on: windows-2022
    env:
      LLVM_BIN: C:\Program Files\LLVM\bin
      LLVM_VERSION: "15.0.1"
    steps:
      # This step is important to make sure scalafmt 
      # checks don't fail
      - name: Setup git config
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6.3
      - uses: VirtusLab/scala-cli-setup@v0.1

      # See https://github.com/scala-native/scala-native/blob/master/.github/actions/windows-setup-env/action.yml#L14 
      # for details
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 4GB
          maximum-size: 16GB

      - name: Install clang
        shell: pwsh
        run: |
          choco install llvm --version="$Env:LLVM_VERSION" --allow-downgrade
          choco install sbt --version=1.7.1
          clang --version

      - name: CI (windows)
        run: scala-cli package --native generated test.scala -f -o scip-json-cli.exe --native-mode release-fast
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          path: scip-json-cli.exe
          name: scip-json-cli-x86_64-pc-win32
          if-no-files-found: error

  release:
    needs: [unix_build, windows_build]
    name: Release
    if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    env: 
      BINARIES: binaries/
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Download binaries
        uses: actions/download-artifact@v3
        id: download
        with:
          path: binaries

      - name: Rename binaries 
        run: |
          cd "${{steps.download.outputs.download-path}}"
          mv scip-json-cli-x86_64-apple-darwin scip-json-cli-x86_64-apple-darwin-dir
          mv scip-json-cli-x86_64-apple-darwin-dir/scip-json-cli scip-json-cli-x86_64-apple-darwin

          mv scip-json-cli-x86_64-pc-linux scip-json-cli-x86_64-pc-linux-dir
          mv scip-json-cli-x86_64-pc-linux-dir/scip-json-cli scip-json-cli-x86_64-pc-linux

          mv scip-json-cli-x86_64-pc-win32 scip-json-cli-x86_64-pc-win32-dir
          mv scip-json-cli-x86_64-pc-win32-dir/scip-json-cli.exe scip-json-cli-x86_64-pc-win32.exe

      - name: Upload release binaries
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{steps.download.outputs.download-path}}/**/*"
